[package]
name = "mpsu_ca"
version = "0.1.0"
authors = ["Jelle Vos <J.V.Vos@tudelft.nl>"]
edition = "2018"

[dependencies]
curve25519-dalek = "3"
rand = "0.7"
bytevec = "0.2.0"
permutation_iterator = "0.1.2"
structopt = "0.3"
sets_multisets = "0.6"
xxh3 = "0.1"
